apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: shipwright-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    app: shipwright-operator
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      app: shipwright-operator
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: shipwright-operator
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - args:
        - --leader-elect
        env:
        - name: USE_MANAGED_WEBHOOK_CERTS
          value: "true"
        image: ko://github.com/shipwright-io/operator
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: operator
      terminationGracePeriodSeconds: 10
