apiVersion: v1
kind: Service
metadata:
  labels:
    app: shipwright-operator
  name: operator-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: shipwright-operator
    control-plane: controller-manager
