resources:
- ../default
- ../samples
- ../scorecard

# Patch for removing the cert manager for OLM deployments
# This is only necessary if the cert manager volumes are added to the main deployment as part of
# adding a mutating/validating admission webhook.
# See https://sdk.operatorframework.io/docs/building-operators/golang/webhook/ and
# https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.6.1/#manifestsv2-add-a-kustomize-patch-to-remove-the-cert-manager-volumevolumemount-from-your-csv

#patchesJson6902:
#- target:
#    group: apps
#    version: v1
#    kind: Deployment
#    name: operator
#    namespace: system
#  patch: |-
#    # Remove the manager container's "cert" volumeMount, since OLM will create and mount a set of certs.
#    # Update the indices in this path if adding or removing containers/volumeMounts in the manager's Deployment.
#    - op: remove
#      path: /spec/template/spec/containers/1/volumeMounts/0
#    # Remove the "cert" volume, since OLM will create and mount a set of certs.
#    # Update the indices in this path if adding or removing volumes in the manager's Deployment.
#    - op: remove
#      path: /spec/template/spec/volumes/0
